# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: librarySystem.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'librarySystem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13librarySystem.proto\x12\nhelloworld\"*\n\x0cHelloRequest\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x05\"\x1c\n\nHelloReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\x05\x32G\n\x07Greeter\x12<\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReplyB)\n\x16\x63om.example.helloworldB\x0fHelloWorldProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'librarySystem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.example.helloworldB\017HelloWorldProto'
  _globals['_HELLOREQUEST']._serialized_start=35
  _globals['_HELLOREQUEST']._serialized_end=77
  _globals['_HELLOREPLY']._serialized_start=79
  _globals['_HELLOREPLY']._serialized_end=107
  _globals['_GREETER']._serialized_start=109
  _globals['_GREETER']._serialized_end=180
# @@protoc_insertion_point(module_scope)
